import axios from "axios";
import Head from "next/head";
import Navbar from "../components/Navbar";
import ProductList from "../components/Product/list";

import { useEffect } from "react";
import { useApp } from "../hooks/useApp";
import EditModal from "../components/Modal/edit";

export default function Home({ productlist }) {
  const { appState, setAppState } = useApp();

  useEffect(() => {
    setAppState((prev) => ({ ...prev, productlist }));
  }, [productlist]);

  return (
    <div>
      <Head>
        <title>Mighty Jaxx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {appState.isModalActive && <EditModal />}

      <Navbar>
        <h1 className="text-4xl font-semibold text-dark-brown">
          Admin Dashboard
        </h1>

        <div className="px-10 py-2 rounded-md my-5 md:w-1/3 w-full outline-none">
          <input
            placeholder="Search product..."
            className="px-3 py-2 rounded-md w-full outline-none"
          />
        </div>

        <div className="container mx-auto flex justify-center items-center py-10 text-dark-brown">
          <ProductList />
        </div>
      </Navbar>
    </div>
  );
}

export async function getServerSideProps(context) {
  const productlist = await axios.get("http://localhost:3001/product/1");

  return {
    props: {
      productlist: productlist.data,
    },
  };
}
