import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mighty Jaxx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar>
        <h1 className="text-4xl font-semibold text-dark-brown">
          Admin Dashboard
        </h1>

        <div className="px-10 py-2 rounded-md my-5 md:w-1/3 w-full outline-none">
          <input
            placeholder="Search product..."
            className="px-3 py-2 rounded-md w-full outline-none"
          />
        </div>

        <div className="container mx-auto flex justify-center items-center py-10"></div>
      </Navbar>
    </div>
  );
}
