import Head from "next/head";
import useLocalStorage from "../hooks/useLocalStorage";

import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [token, _] = useLocalStorage("user_token");

  useEffect(() => {
    if (!token) {
      router.push("/login");
    }

    console.log(token);
  }, [token]);

  return (
    <div>
      <Head>
        <title>Mighty Jaxx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-primary min-h-screen flex justify-center items-center"></main>
    </div>
  );
}
